### ISSUE TITLE
FAB Size

### ISSUE THREAD

**Issue by thailey01** [saurabharora90/MaterialArcMenu#11]
I love the updates and everything is great. It would be cool if you could size the button similar to how floating action buttons are sized (e.g. mini or normal) to keep the menu consistent with FAB.

**Comment by saurabharora90** [comment]
Will add it soon.

**Comment by saurabharora90** [comment]
Hi @thailey01 The FAB doesn't provide an API to control the size programatically. With the current design of the library, this won't be possible.
