### ISSUE TITLE
Does is support placement at the top of the screen?

### ISSUE THREAD

**Issue by jay-jlm** [saurabharora90/MaterialArcMenu#12]
If not, please consider adding, should not be hard.

If if does, please consider adding this information to the read me file.

**Comment by saurabharora90** [comment]
it doesn't support yet. I can look into adding it if there is a special need to it.

**Comment by saurabharora90** [comment]
I have added support for placing the menu at the top of the screen but it doesn't support the CoordinatorLayout Behaviour
