### ISSUE TITLE
How to change image of arc menu from java code

### ISSUE THREAD

**Issue by AbbyChandra** [saurabharora90/MaterialArcMenu#19]
app:menu_scr="@drawable/ic_add"
How to achieve this in java code. On menu opened i want to change the image and on menu again the previous image.

**Comment by saurabharora90** [comment]
If you use a vector image use AnimatedStateListDrawable then it should work without any changes needed. Can you give it a shot?

**Comment by AbbyChandra** [comment]
I am not able to find the property "AnimatedStateListDrawable " can you provide the code snippet. And one more thing i am using this in kotlin.

**Comment by saurabharora90** [comment]
Realized I would need to expose the drawable property for this to work. 

Probably can send a PR to enhance this?

**Comment by AbbyChandra** [comment]
> Realized I would need to expose the drawable property for this to work.
> 
> Probably can send a PR to enhance this?

Sorry i didn't get what is PR.
