### ISSUE TITLE
Add License block to pom.xml

### ISSUE THREAD

**Issue by EmmettWilson** [saurabharora90/MaterialArcMenu#20]
Is your feature request related to a problem? Please describe.
Many projects use plugins to generate their Open Source Licenses attribution page in their application. A common way to do this is to inspect the pom.xml in the .aar or .jar. Please add the license block when releasing the project so it is picked up by the tooling.

See:
https://github.com/jaredsburrows/gradle-license-plugin
https://github.com/google/play-services-plugins/tree/master/oss-licenses-plugin

**Comment by saurabharora90** [comment]
Sure! Will do that over the weekend. Also, will update and add support for androidX and probably MDC.
