### ISSUE TITLE
Change radius programatically

### ISSUE THREAD

**Issue by dulangaj** [saurabharora90/MaterialArcMenu#9]
Hi,

Thanks so much for making this. This is the nicest arc menu I have come across, and I love it.

I would like to be able to change the radius of the menu depending on the screen size/resolution, in the java class. (so the radius is always a certain percentage of the screen size)
Is this possible using this library, and if so, would you mind telling me it can be done?

**Comment by saurabharora90** [comment]
Hi,

Currently there isn't a way to do that! I'll add the API soon in a next update.

**Comment by dulangaj** [comment]
Thank you so much!

**Comment by saurabharora90** [comment]
Added support in v1.4

**Comment by dulangaj** [comment]
Thank you!
